/*
 * Copyright 2009 - 2009 by Menya Project
 * 
 * This file is part of Menya.
 * 
 * Menya is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * Menya is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser Public License along with
 * Menya. If not, see <http://www.gnu.org/licenses/>.
 */

/* $Id$ */

package menya.gui;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

import javax.swing.JFileChooser;

/**
 * The main frame of Menya.
 * 
 * @author Max
 * @version $Revision$
 */
@SuppressWarnings("serial")
public class MainFrame extends javax.swing.JFrame {

    private boolean isFullscreen;
    private final GraphicsDevice device = GraphicsEnvironment
            .getLocalGraphicsEnvironment().getDefaultScreenDevice();

    /** Creates new form MainFrame. */
    public MainFrame() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.jToolBar1 = new javax.swing.JToolBar();
        this.buttonFullscreen = new javax.swing.JButton();
        this.buttonOpen = new javax.swing.JButton();
        this.jScrollPane1 = new javax.swing.JScrollPane();
        this.sketchPane1 = new menya.gui.PagePanel();

        this
                .setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setTitle("Menya");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        this.jToolBar1.setRollover(true);

        this.buttonFullscreen.setIcon(new javax.swing.ImageIcon(this.getClass()
                .getResource("/view-fullscreen.png"))); // NOI18N
        this.buttonFullscreen.setText("Fullscreen");
        this.buttonFullscreen.setToolTipText("Enter / Exit Full Screen Mode");
        this.buttonFullscreen.setEnabled(this.device.isFullScreenSupported());
        this.buttonFullscreen.setFocusable(false);
        this.buttonFullscreen
                .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        this.buttonFullscreen
                .setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        this.buttonFullscreen
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(
                            final java.awt.event.ActionEvent evt) {
                        MainFrame.this.fullScreen(evt);
                    }
                });
        this.jToolBar1.add(this.buttonFullscreen);

        this.buttonOpen.setIcon(new javax.swing.ImageIcon(this.getClass()
                .getResource("/document-open.png"))); // NOI18N
        this.buttonOpen.setText("Open");
        this.buttonOpen.setToolTipText("Open an existing Document");
        this.buttonOpen.setFocusable(false);
        this.buttonOpen
                .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        this.buttonOpen
                .setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        this.buttonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                MainFrame.this.openDocument(evt);
            }
        });
        this.jToolBar1.add(this.buttonOpen);

        this.getContentPane().add(this.jToolBar1, java.awt.BorderLayout.NORTH);

        final javax.swing.GroupLayout sketchPane1Layout = new javax.swing.GroupLayout(
                this.sketchPane1);
        this.sketchPane1.setLayout(sketchPane1Layout);
        sketchPane1Layout.setHorizontalGroup(sketchPane1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 595, Short.MAX_VALUE));
        sketchPane1Layout.setVerticalGroup(sketchPane1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 1682, Short.MAX_VALUE));

        this.jScrollPane1.setViewportView(this.sketchPane1);

        this.getContentPane().add(this.jScrollPane1,
                java.awt.BorderLayout.CENTER);

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openDocument(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_openDocument
        // TODO: Use a better file chooser, use Webstart / OSX specific hooks.
        final JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        final String filename = chooser.getSelectedFile().getAbsolutePath();
        this.sketchPane1.load(filename);
        this.validate();
    }// GEN-LAST:event_openDocument

    private void fullScreen(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fullScreen
        this.isFullscreen = !this.isFullscreen;
        if (this.isFullscreen) {
            this.dispose();
            this.setUndecorated(true);
            this.setVisible(true);
            this.device.setFullScreenWindow(this);
        } else {
            this.device.setFullScreenWindow(null);
            this.dispose();
            this.setUndecorated(false);
            this.setVisible(true);
        }
    }// GEN-LAST:event_fullScreen

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFullscreen;
    private javax.swing.JButton buttonOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private menya.gui.PagePanel sketchPane1;
    // End of variables declaration//GEN-END:variables

}
