/*
 * Copyright 2009 - 2009 by Menya Project
 * 
 * This file is part of Menya.
 * 
 * Menya is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * Menya is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser Public License along with
 * Menya. If not, see <http://www.gnu.org/licenses/>.
 */

/* $Id$ */

package menya.gui;

/**
 * The main frame of Menya.
 * 
 * @author Max
 * @version $Revision$
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame. */
    public MainFrame() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.jToolBar1 = new javax.swing.JToolBar();
        this.jButton1 = new javax.swing.JButton();
        this.jScrollPane1 = new javax.swing.JScrollPane();
        this.sketchPane1 = new menya.gui.SketchPane();

        this
                .setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setTitle("Menya");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        this.jToolBar1.setRollover(true);

        this.jButton1.setText("Full");
        this.jButton1.setToolTipText("Enter / Exit Full Screen Mode");
        this.jButton1.setFocusable(false);
        this.jButton1
                .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        this.jButton1
                .setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        this.jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                MainFrame.this.fullScreen(evt);
            }
        });
        this.jToolBar1.add(this.jButton1);

        this.getContentPane().add(this.jToolBar1, java.awt.BorderLayout.NORTH);

        final javax.swing.GroupLayout sketchPane1Layout = new javax.swing.GroupLayout(
                this.sketchPane1);
        this.sketchPane1.setLayout(sketchPane1Layout);
        sketchPane1Layout.setHorizontalGroup(sketchPane1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 800, Short.MAX_VALUE));
        sketchPane1Layout.setVerticalGroup(sketchPane1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 600, Short.MAX_VALUE));

        this.jScrollPane1.setViewportView(this.sketchPane1);

        this.getContentPane().add(this.jScrollPane1,
                java.awt.BorderLayout.CENTER);

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullScreen(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fullScreen
        // TODO implement
    }// GEN-LAST:event_fullScreen

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private menya.gui.SketchPane sketchPane1;
    // End of variables declaration//GEN-END:variables

}
